export default {
  MQTT_BROKER_URL: import.meta.env.VITE_MQTT_BROKER_URL,
  OPENWEATHERMAP_API_KEY: import.meta.env.VITE_OPENWEATHERMAP_API_KEY,
  LOCATION: import.meta.env.VITE_LOCATION,
  INFLUXDB_URL: import.meta.env.VITE_INFLUXDB_URL,
  INFLUXDB_API_TOKEN: import.meta.env.VITE_INFLUXDB_API_TOKEN,
  INFLUXDB_ORG: import.meta.env.VITE_INFLUXDB_ORG,
};
